### ISSUE TITLE
Any way to disable enable with a keypress

### ISSUE THREAD

**Issue by jasonkneen** [joshjensen/related-split-view#1]
Hi Josh,

Love this -- playing with Atom -- would be great if we could have a keypress or something to switch it on and off.

Jason

**Comment by joshjensen** [comment]
Thanks @jasonkneen! I will look into that. I have thought about adding a toggle to it, a hotkey would be perfect.

**Comment by jasonkneen** [comment]
awesome thanks -- loving it -- it's just sometimes I wanted (especially on
laptop screen) to focus back on one window / pane

**Comment by joshjensen** [comment]
I am actually going to close this request in favor of "Hey Pane" since it does essentially what this would do and is compatible with this module.

https://atom.io/packages/hey-pane
