### ISSUE TITLE
uri.indexOf is not a function & stack size exceeded errors

### ISSUE THREAD

**Issue by jasonkneen** [joshjensen/related-split-view#3]
Launching today running version 1.17.0 of Atom and latest related-split-view.

Errors and locks up Atom -- have to uninstall the package for anything to work.

**Comment by joshjensen** [comment]
Unfortunately, Atom changed how the panes are handled which broke how the module interacts with those panes. This is beyond my Coffeescript or Atom Fu so I am going to have to sunset this module unless someone else would like to create a PR.

**Comment by joshjensen** [comment]
Fixed in version 0.3.1

**Comment by jasonkneen** [comment]
yay!
